/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package gov.nasa.jpl.xdata.nba.impoexpo.structs;  
@SuppressWarnings("all")
public class Officials extends org.apache.gora.persistency.impl.PersistentBase implements org.apache.avro.specific.SpecificRecord, org.apache.gora.persistency.Persistent {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Officials\",\"namespace\":\"gov.nasa.jpl.xdata.nba.impoexpo.structs\",\"fields\":[{\"name\":\"officialId\",\"type\":\"int\",\"default\":0},{\"name\":\"firstName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lastName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"jerseyNum\",\"type\":\"int\",\"default\":0}]}");

  /** Enum containing all data bean's fields. */
  public static enum Field {
    OFFICIAL_ID(0, "officialId"),
    FIRST_NAME(1, "firstName"),
    LAST_NAME(2, "lastName"),
    JERSEY_NUM(3, "jerseyNum"),
    ;
    /**
     * Field's index.
     */
    private int index;

    /**
     * Field's name.
     */
    private String name;

    /**
     * Field's constructor
     * @param index field's index.
     * @param name field's name.
     */
    Field(int index, String name) {this.index=index;this.name=name;}

    /**
     * Gets field's index.
     * @return int field's index.
     */
    public int getIndex() {return index;}

    /**
     * Gets field's name.
     * @return String field's name.
     */
    public String getName() {return name;}

    /**
     * Gets field's attributes to string.
     * @return String field's attributes to string.
     */
    public String toString() {return name;}
  };

  public static final String[] _ALL_FIELDS = {
  "officialId",
  "firstName",
  "lastName",
  "jerseyNum",
  };

  /**
   * Gets the total field count.
   * @return int field count
   */
  public int getFieldsCount() {
    return Officials._ALL_FIELDS.length;
  }

  private int officialId;
  private java.lang.CharSequence firstName;
  private java.lang.CharSequence lastName;
  private int jerseyNum;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return officialId;
    case 1: return firstName;
    case 2: return lastName;
    case 3: return jerseyNum;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value) {
    switch (field$) {
    case 0: officialId = (java.lang.Integer)(value); break;
    case 1: firstName = (java.lang.CharSequence)(value); break;
    case 2: lastName = (java.lang.CharSequence)(value); break;
    case 3: jerseyNum = (java.lang.Integer)(value); break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'officialId' field.
   */
  public java.lang.Integer getOfficialId() {
    return officialId;
  }

  /**
   * Sets the value of the 'officialId' field.
   * @param value the value to set.
   */
  public void setOfficialId(java.lang.Integer value) {
    this.officialId = value;
    setDirty(0);
  }
  
  /**
   * Checks the dirty status of the 'officialId' field. A field is dirty if it represents a change that has not yet been written to the database.
   * @param value the value to set.
   */
  public boolean isOfficialIdDirty(java.lang.Integer value) {
    return isDirty(0);
  }

  /**
   * Gets the value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }

  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
    setDirty(1);
  }
  
  /**
   * Checks the dirty status of the 'firstName' field. A field is dirty if it represents a change that has not yet been written to the database.
   * @param value the value to set.
   */
  public boolean isFirstNameDirty(java.lang.CharSequence value) {
    return isDirty(1);
  }

  /**
   * Gets the value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }

  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
    setDirty(2);
  }
  
  /**
   * Checks the dirty status of the 'lastName' field. A field is dirty if it represents a change that has not yet been written to the database.
   * @param value the value to set.
   */
  public boolean isLastNameDirty(java.lang.CharSequence value) {
    return isDirty(2);
  }

  /**
   * Gets the value of the 'jerseyNum' field.
   */
  public java.lang.Integer getJerseyNum() {
    return jerseyNum;
  }

  /**
   * Sets the value of the 'jerseyNum' field.
   * @param value the value to set.
   */
  public void setJerseyNum(java.lang.Integer value) {
    this.jerseyNum = value;
    setDirty(3);
  }
  
  /**
   * Checks the dirty status of the 'jerseyNum' field. A field is dirty if it represents a change that has not yet been written to the database.
   * @param value the value to set.
   */
  public boolean isJerseyNumDirty(java.lang.Integer value) {
    return isDirty(3);
  }

  /** Creates a new Officials RecordBuilder */
  public static gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder newBuilder() {
    return new gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder();
  }
  
  /** Creates a new Officials RecordBuilder by copying an existing Builder */
  public static gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder newBuilder(gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder other) {
    return new gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder(other);
  }
  
  /** Creates a new Officials RecordBuilder by copying an existing Officials instance */
  public static gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder newBuilder(gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials other) {
    return new gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder(other);
  }
  
  private static java.nio.ByteBuffer deepCopyToReadOnlyBuffer(
      java.nio.ByteBuffer input) {
    java.nio.ByteBuffer copy = java.nio.ByteBuffer.allocate(input.capacity());
    int position = input.position();
    input.reset();
    int mark = input.position();
    int limit = input.limit();
    input.rewind();
    input.limit(input.capacity());
    copy.put(input);
    input.rewind();
    copy.rewind();
    input.position(mark);
    input.mark();
    copy.position(mark);
    copy.mark();
    input.position(position);
    copy.position(position);
    input.limit(limit);
    copy.limit(limit);
    return copy.asReadOnlyBuffer();
  }
  
  /**
   * RecordBuilder for Officials instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Officials>
    implements org.apache.avro.data.RecordBuilder<Officials> {

    private int officialId;
    private java.lang.CharSequence firstName;
    private java.lang.CharSequence lastName;
    private int jerseyNum;

    /** Creates a new Builder */
    private Builder() {
      super(gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Officials instance */
    private Builder(gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials other) {
            super(gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.SCHEMA$);
      if (isValidValue(fields()[0], other.officialId)) {
        this.officialId = (java.lang.Integer) data().deepCopy(fields()[0].schema(), other.officialId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.firstName)) {
        this.firstName = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.firstName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.jerseyNum)) {
        this.jerseyNum = (java.lang.Integer) data().deepCopy(fields()[3].schema(), other.jerseyNum);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'officialId' field */
    public java.lang.Integer getOfficialId() {
      return officialId;
    }
    
    /** Sets the value of the 'officialId' field */
    public gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder setOfficialId(int value) {
      validate(fields()[0], value);
      this.officialId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'officialId' field has been set */
    public boolean hasOfficialId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'officialId' field */
    public gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder clearOfficialId() {
      fieldSetFlags()[0] = false;
      return this;
    }
    
    /** Gets the value of the 'firstName' field */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }
    
    /** Sets the value of the 'firstName' field */
    public gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.firstName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'firstName' field has been set */
    public boolean hasFirstName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'firstName' field */
    public gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[1] = false;
      return this;
    }
    
    /** Gets the value of the 'lastName' field */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }
    
    /** Sets the value of the 'lastName' field */
    public gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.lastName = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'lastName' field has been set */
    public boolean hasLastName() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'lastName' field */
    public gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[2] = false;
      return this;
    }
    
    /** Gets the value of the 'jerseyNum' field */
    public java.lang.Integer getJerseyNum() {
      return jerseyNum;
    }
    
    /** Sets the value of the 'jerseyNum' field */
    public gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder setJerseyNum(int value) {
      validate(fields()[3], value);
      this.jerseyNum = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'jerseyNum' field has been set */
    public boolean hasJerseyNum() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'jerseyNum' field */
    public gov.nasa.jpl.xdata.nba.impoexpo.structs.Officials.Builder clearJerseyNum() {
      fieldSetFlags()[3] = false;
      return this;
    }
    
    @Override
    public Officials build() {
      try {
        Officials record = new Officials();
        record.officialId = fieldSetFlags()[0] ? this.officialId : (java.lang.Integer) defaultValue(fields()[0]);
        record.firstName = fieldSetFlags()[1] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.lastName = fieldSetFlags()[2] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.jerseyNum = fieldSetFlags()[3] ? this.jerseyNum : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
  
  public Officials.Tombstone getTombstone(){
  	return TOMBSTONE;
  }

  public Officials newInstance(){
    return newBuilder().build();
  }

  private static final Tombstone TOMBSTONE = new Tombstone();
  
  public static final class Tombstone extends Officials implements org.apache.gora.persistency.Tombstone {
  
      private Tombstone() { }
  
	  		  /**
	   * Gets the value of the 'officialId' field.
		   */
	  public java.lang.Integer getOfficialId() {
	    throw new java.lang.UnsupportedOperationException("Get is not supported on tombstones");
	  }
	
	  /**
	   * Sets the value of the 'officialId' field.
		   * @param value the value to set.
	   */
	  public void setOfficialId(java.lang.Integer value) {
	    throw new java.lang.UnsupportedOperationException("Set is not supported on tombstones");
	  }
	  
	  /**
	   * Checks the dirty status of the 'officialId' field. A field is dirty if it represents a change that has not yet been written to the database.
		   * @param value the value to set.
	   */
	  public boolean isOfficialIdDirty(java.lang.Integer value) {
	    throw new java.lang.UnsupportedOperationException("IsDirty is not supported on tombstones");
	  }
	
				  /**
	   * Gets the value of the 'firstName' field.
		   */
	  public java.lang.CharSequence getFirstName() {
	    throw new java.lang.UnsupportedOperationException("Get is not supported on tombstones");
	  }
	
	  /**
	   * Sets the value of the 'firstName' field.
		   * @param value the value to set.
	   */
	  public void setFirstName(java.lang.CharSequence value) {
	    throw new java.lang.UnsupportedOperationException("Set is not supported on tombstones");
	  }
	  
	  /**
	   * Checks the dirty status of the 'firstName' field. A field is dirty if it represents a change that has not yet been written to the database.
		   * @param value the value to set.
	   */
	  public boolean isFirstNameDirty(java.lang.CharSequence value) {
	    throw new java.lang.UnsupportedOperationException("IsDirty is not supported on tombstones");
	  }
	
				  /**
	   * Gets the value of the 'lastName' field.
		   */
	  public java.lang.CharSequence getLastName() {
	    throw new java.lang.UnsupportedOperationException("Get is not supported on tombstones");
	  }
	
	  /**
	   * Sets the value of the 'lastName' field.
		   * @param value the value to set.
	   */
	  public void setLastName(java.lang.CharSequence value) {
	    throw new java.lang.UnsupportedOperationException("Set is not supported on tombstones");
	  }
	  
	  /**
	   * Checks the dirty status of the 'lastName' field. A field is dirty if it represents a change that has not yet been written to the database.
		   * @param value the value to set.
	   */
	  public boolean isLastNameDirty(java.lang.CharSequence value) {
	    throw new java.lang.UnsupportedOperationException("IsDirty is not supported on tombstones");
	  }
	
				  /**
	   * Gets the value of the 'jerseyNum' field.
		   */
	  public java.lang.Integer getJerseyNum() {
	    throw new java.lang.UnsupportedOperationException("Get is not supported on tombstones");
	  }
	
	  /**
	   * Sets the value of the 'jerseyNum' field.
		   * @param value the value to set.
	   */
	  public void setJerseyNum(java.lang.Integer value) {
	    throw new java.lang.UnsupportedOperationException("Set is not supported on tombstones");
	  }
	  
	  /**
	   * Checks the dirty status of the 'jerseyNum' field. A field is dirty if it represents a change that has not yet been written to the database.
		   * @param value the value to set.
	   */
	  public boolean isJerseyNumDirty(java.lang.Integer value) {
	    throw new java.lang.UnsupportedOperationException("IsDirty is not supported on tombstones");
	  }
	
		  
  }
  
}

